// Package generator builds the Simplified Technical English vocabulary source
// file from the vendored OpenSTE wordset. Both "vale gen" and "go generate"
// call this package, so the two ways always make the same output.
package generator

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"github.com/stuffbucket/vale/internal/vocab"
)

// wordset is the shape of the OpenSTE JSON file. The generator reads the
// alternatives, which hold the unapproved-to-approved word pairs, and the
// words, which hold the status of each word.
type wordset struct {
	SetName     string `json:"set_name"`
	Description string `json:"description"`
	Words       []struct {
		Title      string `json:"title"`
		WordStatus string `json:"wordstatus"`
	} `json:"words"`
	Alternatives []struct {
		Title    string `json:"title"`
		AltTitle string `json:"alt_title"`
	} `json:"alternatives"`
}

// titlePattern keeps clean word and phrase titles. It drops titles that hold
// notes in parentheses or other marks that are not part of the word itself.
var titlePattern = regexp.MustCompile(`^[a-z]+(?:[-' ][a-z]+)*$`)

// Build reads the wordset JSON and returns the substitutions in a stable order.
func Build(jsonData []byte) ([]vocab.Substitution, error) {
	var ws wordset
	if err := json.Unmarshal(jsonData, &ws); err != nil {
		return nil, fmt.Errorf("parse wordset: %w", err)
	}
	return buildSubs(ws), nil
}

func buildSubs(ws wordset) []vocab.Substitution {
	grouped := map[string][]string{}
	seen := map[string]map[string]bool{}
	for _, a := range ws.Alternatives {
		title := a.Title
		alt := a.AltTitle
		if !titlePattern.MatchString(title) || alt == "" {
			continue
		}
		// Drop an alternative that is the same as the word itself.
		if strings.EqualFold(alt, title) {
			continue
		}
		if seen[title] == nil {
			seen[title] = map[string]bool{}
		}
		if seen[title][alt] {
			continue
		}
		seen[title][alt] = true
		grouped[title] = append(grouped[title], alt)
	}
	subs := make([]vocab.Substitution, 0, len(grouped))
	for word, alts := range grouped {
		subs = append(subs, vocab.Substitution{Word: word, Alternatives: alts})
	}
	sort.Slice(subs, func(i, j int) bool { return subs[i].Word < subs[j].Word })
	return subs
}

// buildUnapproved returns the unapproved words that have no substitution pair.
// The strict vocabulary check uses this bare list.
func buildUnapproved(ws wordset, subs []vocab.Substitution) []string {
	hasSub := map[string]bool{}
	for _, s := range subs {
		hasSub[s.Word] = true
	}
	seen := map[string]bool{}
	var out []string
	for _, w := range ws.Words {
		title := w.Title
		if w.WordStatus != "unapproved" || !titlePattern.MatchString(title) {
			continue
		}
		if hasSub[title] || seen[title] {
			continue
		}
		seen[title] = true
		out = append(out, title)
	}
	sort.Strings(out)
	return out
}

// fileTemplate is the layout of the generated source file.
const fileTemplate = `// Code generated by "vale gen" from third_party/openste/openste.json. DO NOT EDIT.
//
// Source: OpenSTE wordset ({{.SetName}}), MIT license, (c) openSTE.org.
// See third_party/openste/LICENSE and third_party/openste/PROVENANCE.txt.
// This data is an approximation of ASD-STE100. It is not certified. The ASD
// dictionary itself is copyrighted and is not bundled.

package vocab

// Substitutions holds {{len .Subs}} unapproved words and phrases with approved
// replacements, built from the OpenSTE wordset.
var Substitutions = []Substitution{
{{- range .Subs}}
	{Word: {{printf "%q" .Word}}, Alternatives: []string{ {{range $i, $a := .Alternatives}}{{if $i}}, {{end}}{{printf "%q" $a}}{{end}} }},
{{- end}}
}

// UnapprovedWords holds {{len .Unapproved}} words that OpenSTE marks as
// unapproved but gives no direct replacement for. The strict vocabulary check
// uses this list. It is off by default because it makes many findings on
// ordinary prose.
var UnapprovedWords = []string{
{{- range .Unapproved}}
	{{printf "%q" .}},
{{- end}}
}
`

// Render turns the substitutions and the unapproved list into formatted Go
// source.
func Render(setName string, subs []vocab.Substitution, unapproved []string) ([]byte, error) {
	tmpl, err := template.New("vocab").Parse(fileTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	data := struct {
		SetName    string
		Subs       []vocab.Substitution
		Unapproved []string
	}{SetName: setName, Subs: subs, Unapproved: unapproved}
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

// Generate reads the wordset at inPath, builds the data, and writes the
// generated source to outPath. It returns the number of substitutions.
func Generate(inPath, outPath string) (int, error) {
	raw, err := os.ReadFile(inPath)
	if err != nil {
		return 0, fmt.Errorf("read wordset: %w", err)
	}
	var ws wordset
	if err := json.Unmarshal(raw, &ws); err != nil {
		return 0, fmt.Errorf("parse wordset: %w", err)
	}
	subs := buildSubs(ws)
	unapproved := buildUnapproved(ws, subs)
	out, err := Render(ws.SetName, subs, unapproved)
	if err != nil {
		return 0, err
	}
	if err := os.WriteFile(outPath, out, 0o644); err != nil {
		return 0, fmt.Errorf("write output: %w", err)
	}
	return len(subs), nil
}
